{
is_ring_available: false, 
# 1 for ouster LiDAR, 2 for velodyne LiDAR
# lidar_type: 1, 

scan_frequency: 10,

lidar_vfov: 45.0, 
lidar_vfov_upper: 22.5, 
lidar_vfov_lower: -22.5, 

lidar_hfov: 360.0, 
lidar_lines: 31, 
lidar_hresolution: 511, 

blind: 0.3, 
}